language: android
install: true

env:
  - ANDROID_HOME=~/android/sdk

before_install:
    - yes | sdkmanager "platforms;android-27"

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew build --scan -s
