language: android
install: true

env:
  - ANDROID_HOME=~/android/sdk

before_install:
    - yes | sdkmanager "build-tools;27.0.1"
     - ANDROID_BUILD_TOOLS=27.0.1

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew build --scan -s
